spring:
  thymeleaf:
    cache: false
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    #监控统计拦截的filters
      filter: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.56.1:3306/hs_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      #空闲连接是否被回收
      test-while-idle: true
      #申请连接时是否检测有效性
      test-on-borrow: false
      #归还连接时是否检测有效性
      test-on-return: false
  redis:
    host: 127.0.0.1
    port: 6379
  #  password: root
mybatis:
# mapper映射文件
  mapper-locations: classpath:com/codefei/boot2/*/mapper/*.xml
  #  别名
  type-aliases-package: com.codefei.boot2
logging:
  level:
    org.thymeleaf: info
pagehelper:
  reasonable: true