server:
  port: 8888

jdbc:
  url: jdbc:mysql://localhost:3306/aa
  driverClassName: com.codefei.Driver
  username: root
  password: root
  name: mysql数据库连接
  ips: [aa,bb,cc]
  dsMap: {key1: aaaa,key2: bbbb}
  dsDate: 2015/12/12 13:22:22
spring:
  thymeleaf:
    cache: false